In [ ]:
import numpy as np

In [ ]:
n = 3

In [ ]:
2 ** 3

8

In [ ]:
120

120

In [ ]:
x = 5

In [ ]:
np.int8

numpy.int8

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([0, 1.5, 1, 2.5])

In [ ]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [ ]:
a[0:]

array([1, 2, 3, 4])

b[0], b[3]

In [ ]:
a[::3]

array([1, 4])

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [ ]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [ ]:
a = np.arange(5)
print(a<=3)

[ True  True  True  True False]
